name: bluebuild
on:
  schedule:
    - cron: "00 18 * * 5"
  push:
    paths-ignore:
      - "**.md"

  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          # - recipe-myos-gnome-main.yml
          # - recipe-myos-gnome-nvidia.yml
          # - recipe-myos-hyprland-main.yml
          # - recipe-myos-hyprland-nvidia.yml
          - recipe-myos-sway-main.yml
          - recipe-myos-sway-nvidia.yml
          # - recipe-myos-wayfire-main.yml
          # - recipe-myos-wayfire-nvidia.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.9.1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
